### ISSUE TITLE
反馈

### ISSUE THREAD

**Issue by ti0s** [EASY233/Finger#1]
感谢大佬开发如此趁手的工具，但是有一个问题，就是我在win使用正常，但是在mac和centos7上到[09:21:38] [+] 是否开启了MD5指纹识别:False就卡死不动了

**Comment by EASY233** [comment]
首先非常感谢大佬的使用与反馈，这两天比较忙估计明天才有空认真看一下代码修复bug。主要是该项目在实战使用中我觉得有点差强人意，计划重写。如果你现在有迫切需要的话我推荐使用该项目:EdgeSecurityTeam/EHole: EHole(棱洞)2.0 重构版-红队重点攻击系统指纹探测工具 (github.com),这也是我学习的目标。再次感谢你的使用，bug修复会第一时间通知你。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "EASY233/Finger"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月22日(星期六) 上午9:26
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[EASY233/Finger] 反馈 (#1)





 
感谢大佬开发如此趁手的工具，但是有一个问题，就是我在win使用正常，但是在mac和centos7上到[09:21:38] [+] 是否开启了MD5指纹识别:False就卡死不动了

**Comment by ti0s** [comment]
感谢大佬回复   工具不着急，静等大佬开发更加趁手的工具

**Comment by EASY233** [comment]
你好，我重新修改了工具之前有点忙一直拖到现在才整好。诚邀你进行测试使用
