### ISSUE TITLE
想问下cdn cidr是怎么判断的

### ISSUE THREAD

**Issue by z2p** [EASY233/Finger#17]
为什么这个表的IP段就是CDN呢？怎么判断的，想了解一下

**Comment by EASY233** [comment]
这些是腾讯、阿里、百度云等常用CDN节点的IP段

**Comment by ybdt** [comment]
最近在写个工具，想使用师傅的这个cdn cidr，师傅怎么获取的这些节点啊

**Comment by EASY233** [comment]
这个也是在网络搜集的，主要是一些常见厂商的cdn段



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月19日(星期二) 下午2:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [EASY233/Finger] 想问下cdn cidr是怎么判断的 (Issue #17)





 
最近在写个工具，想使用师傅的这个cdn cidr，师傅怎么获取的这些节点啊
