### ISSUE TITLE
扫描自动挂掉

### ISSUE THREAD

**Issue by Xm17** [EASY233/Finger#2]
![image](https://user-images.githubusercontent.com/27048404/121653989-d4abc500-cacf-11eb-8152-1a1a317d3ec7.png)
没输出报告，挂掉了

**Comment by EASY233** [comment]
你好，Finger不支持cmd，主要是cmd太不好用了所以在开发的时候没考虑它，windows下建议使用windows terminal或者cmder如果还会出现该情况请在私聊我，感谢你的使用！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月11日(星期五) 下午4:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [EASY233/Finger] 扫描自动挂掉 (#2)





 

 没输出报告，挂掉了

**Comment by Xm17** [comment]
好的 我试试
