### ISSUE TITLE
在线指纹库更新失败，没有指纹信息

### ISSUE THREAD

**Issue by shibingxang** [EASY233/Finger#24]
![image](https://user-images.githubusercontent.com/89562694/170972165-5768e998-29e3-433d-a6b8-f919fabe4ae0.png)

**Comment by QingyuWang-China** [comment]
我也是这种情况，你解决了吗，大佬

**Comment by EASY233** [comment]
指纹更新失败这个不影响程序的运行，应该是网络问题导致的更新失败。没有指纹信息那里你检查一下是否这些url都无法访问

**Comment by EASY233** [comment]
此外可以更新一下Finger到最新版本，最新版本能够看到所有请求失败URL的失败信息

**Comment by Zack-Huang** [comment]
问题还是存在，已经是最新版本

**Comment by huaiyi255** [comment]
> 问题还是存在的，已经是最新版本

实在不行，在config/config.py中，将FingerPrint_Update = True改一下吧，这个为默认检查指纹库，反正实际用的为最新的指纹库文件，检查和不检查没意义了
