### ISSUE TITLE
fofa查询数量

### ISSUE THREAD

**Issue by WaNg-21** [EASY233/Finger#32]
修改了config,py里面的fofa配置参数
![image](https://user-images.githubusercontent.com/57787511/186715086-f17bbfa8-065d-4557-ad48-4008ca60e7e0.png)
运行显示还是100
![image](https://user-images.githubusercontent.com/57787511/186714761-4052b87e-677d-49bd-93b1-0de5f26cd1ee.png)

**Comment by EASY233** [comment]
感谢，当时测试的时候硬编码了这个查询数量(手动捂脸🤦‍♂️)上传的时候忘记改了

**Comment by EASY233** [comment]
已修复
