### ISSUE TITLE
readline 模块太旧，m1无法安装

### ISSUE THREAD

**Issue by lingwu111** [EASY233/Finger#33]
<img width="1315" alt="image" src="https://user-images.githubusercontent.com/28818796/187236268-5fea2284-324f-42c1-9210-106dcbcaed78.png">

**Comment by EASY233** [comment]
安装的模块是pyreadline

**Comment by EASY233** [comment]
我使用的机器也是m1，安装使用没有问题

**Comment by lingwu111** [comment]
大佬好，我这里是这个情况，google搜报错，也搜到这个项目下有相同的情况，但是那个页面404了，不知道那个人解决了没有。
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/28818796/188668935-28b5d204-2408-453a-9c7a-b4584c15d2ed.png">
