### ISSUE TITLE
pbootcms finger

### ISSUE THREAD

**Issue by popcornnnn** [EASY233/Finger#35]
今天发现里面没有pbootcms的指纹，自己加进去的话每次已更新就没了，不更新的话又难以保持最新指纹库，只有师傅你这里帮忙加到库里去了
{
	"cms": "pbootCms",
	"method": "keyword",
	"location": "body",
	"keyword": ["!-- 幻灯片 --", "!--占位导航栏--"]
}

**Comment by EASY233** [comment]
感谢已添加
