### ISSUE TITLE
在线更新指纹库失败，报错信息是valueError

### ISSUE THREAD

**Issue by chu56** [EASY233/Finger#48]
![Snipaste_2023-07-11_17-00-05](https://github.com/EASY233/Finger/assets/117263742/616da7a5-1bb8-4185-9cb6-79f34f8c4973)

**Comment by EASY233** [comment]
可以多访问几次，这个在线更新地址https://cdn.jsdelivr.net/gh/EASY233/Finger/library/finger.json
