### ISSUE TITLE
扫描的时候没有任何提示，输出结果Title都是报错信息

### ISSUE THREAD

**Issue by yuan-boss** [EASY233/Finger#51]
我扫描的命令是 python Finger.py -f  1.txt -o xlsx
1.txt里面有10000个url
扫描没有任何提示：
![qq](https://github.com/EASY233/Finger/assets/81558724/3e37ad4a-d775-4074-8aef-9a06332b482f)
输出的xlsx文件的Title都是报错信息：
![fingle](https://github.com/EASY233/Finger/assets/81558724/f734d23b-164a-472c-897b-335d00464ea1)

**Comment by EASY233** [comment]
缺少了依赖，你先安装一下requests.txt里面的依赖



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月16日(星期四) 中午12:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [EASY233/Finger] 扫描的时候没有任何提示，输出结果Title都是报错信息 (Issue #51)





 
我扫描的命令是 python Finger.py -f  1.txt -o xlsx
 1.txt里面有10000个url
 扫描没有任何提示：
 
 输出的xlsx文件的Title都是报错信息：
