### ISSUE TITLE
功能添加

### ISSUE THREAD

**Issue by zhouchi0402** [EASY233/Finger#6]
建议加入是否跟随跳转功能

**Comment by EASY233** [comment]
感谢提供建议，默认是跟随跳转的，后续可以考虑把是否跟随跳转添加到配置文件中




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月31日(星期六) 下午4:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [EASY233/Finger] 功能添加 (#6)





 
建议加入是否跟随跳转功能
