### ISSUE TITLE
功能优化

### ISSUE THREAD

**Issue by clasy0947** [EASY233/Finger#7]
现在在targets.txt中填入一个IP:端口，会默认用http进行扫描，如果有返回就不会进行https扫描。
![image](https://user-images.githubusercontent.com/79400678/128153378-159df747-d490-4c23-827c-87fbc660a970.png)
我认为可以对`400 The plain HTTP request was sent to HTTPS port`进行特征识别，然后对匹配到的进行HTTPS扫描识别。

**Comment by EASY233** [comment]
后续会进行优化，感谢提供建议
