### ISSUE TITLE
这种问题该怎解啊ModuleNotFoundError: No module named 'lib.cmdline'

### ISSUE THREAD

**Issue by Ymigmli** [EASY233/Finger#8]
![image](https://user-images.githubusercontent.com/47731874/130593803-1b76c386-36b1-4b0e-b0d9-2eedbe8d0b63.png)

![image](https://user-images.githubusercontent.com/47731874/130593638-15c782ba-3007-469f-9a7c-131d0c9ac890.png)

![image](https://user-images.githubusercontent.com/47731874/130593966-46933159-8643-4e9f-be3b-53846e99f4d8.png)

**Comment by EASY233** [comment]
你是不是没有把所有文件解压到一个目录？

**Comment by Ymigmli** [comment]
解压到一个目录了。

**Comment by Ymigmli** [comment]
![image](https://user-images.githubusercontent.com/47731874/131272421-2f829bcd-23bd-48ef-80f7-1c6abf0487b7.png)

**Comment by Ymigmli** [comment]
已解决，python问题，谢谢。
